<?php

/*
 * Implements hook_menu().
 */
function db_demo_menu() {
  $items = array();

  $items['admin/reports/node-list'] = array(
    'title' => 'List of Nodes',
    'description' => t('A list of nodes with published status.'),
    'page callback' => 'db_demo_node_list',
    'access arguments' => array('administer content'),
  );

  return $items;
}

/*
 * Custom page callback for admin/reports/node-list
 */
function db_demo_node_list(){

  // define variants
  $node_types = node_type_get_types();
  #krumo($node_types);
  $stati = array(0, 1); // 0 = unp, 1 = publ

  // loop through variants
  foreach ($node_types as $type) {
    #krumo($type);
    $typename = $type->type;
    foreach($stati as $status) {
      #krumo($status);
      // SELECT COUNT FROM node WHERE type = $typename AND status = $status
      $query = db_select('node', 'n')
        ->condition('type', $typename)
        ->condition('status', $status);
      $query->addExpression('COUNT (nid)', 'node_count');
      $results = $query->execute();
      $data = $results->fetchObject();
      #krumo($data);

      // assign vars for printing
      if ($status == 0) {
        $status = 'unpublished';
      }
      else {
        $status = 'published';
      }

      $items[] = t('The %type content type has %num %status node.', array('%type'=>$typename, '%num'=>$data->node_count, '%status'=>$status));
    } // end status loop
  } // end node type loop
  #krumo($items);

  $content['node-list'] = array(
    '#items' => $items,
    '#theme' => 'item_list',
  );

  return render($content);
}
