<?php

/**
 * Implements hook_node_view().
 */
function demo2_node_view($node, $view_mode = 'full') {
  //only when looking at the full version, NOT the teaser
  if ($view_mode == 'full') {

    global $user;
    // Everytime a node is viewed, increment the node_views count
    // in the demo2 table by one and include the result in the node content

    // Get record
    $record = demo2_get_record($node->nid, $user->uid);

    // If no record, create one we can insert later
    if ($record === FALSE) {
      $record = new StdClass();
      $record->nid = $node->nid;
      $record->uid = $user->uid;
      $record->view_count = 0;
      $record->last_viewed = time();
    }

    // Increment view_count by 1
    $record->view_count++;

    // Update last_viewed
    $record->last_viewed = time();

    // Set the record
    demo2_set_record($record);

    // krumo($record);

    // Set up an array of placeholders to pass to t().
    $t_args = array(
      '%num' => $record->view_count,
      '%date' => date('M j, Y', $record->last_viewed),
    );

    $node->content['node_views'] = array(
      '#markup' => t('You have viewed this page %num times. It was last viewed by you on %date', $t_args),
      '#weight' => 10,
    );
  }
}

/**
 * Gets the record
 */
function demo2_get_record($nid, $uid) {
  // SELECT view_count FROM demo2 WHERE nid = $nid & uid = $uid
  $query = db_select('demo2', 'd')
    ->fields('d', array('nid', 'uid', 'view_count', 'last_viewed'))
    ->condition('nid', $nid)
    ->condition('uid', $uid);
  $record = $query->execute()->fetch();
  return $record;
}

/**
 * Saves a record
 */
function demo2_set_record($record) {
  // sanity check
  if (!is_object($record)) {
    return watchdog('demo2', 'We could not update the info about node views', array(), WATCHDOG_ERROR);
  }

  // INSERT/UPDATE into demo2 ('nid', 'uid', 'node_views') VALUES ('nid', 'uid', 'node_views')
  $query = db_merge('demo2')
    ->key(array('nid' => $record->nid))
    ->key(array('uid' => $record->uid))
    ->fields((array) $record);
  $query->execute();
}
