<?php // $Id$
   /**
    * @file
    * User Warn module file
    *
    * This module allows site administrators to send a stock warning
    * e-mail to a specified user or users through the admin interface.
    * Administrators
    * can configure the default e-mail including token replacement.
    */

   /**
    * Implement hook_help().
    */
   function user_warn_help($path, $arg) {
     if ($path == 'admin/help#user_warn') {
       return t('User Warn allows site administrators to send a standard
   e-mail to site users to notify them of improper behavior.');
} }

 /**
   * Implement hook_menu().
   */
   function user_warn_menu() {
     $items = array();
     $items['admin/config/people/user_warn'] = array(
       'title' => 'User Warn',
       'description' => 'Configuration for the User Warn module.',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('user_warn_form'),
       'access arguments' => array('administer users'),
       'type' => MENU_NORMAL_ITEM,
    );

     $items['user/%/warn'] = array(
       'title' => 'Warn',
       'description' =>
             'Send e-mail to a user about improper site behavior.',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('user_warn_confirm_form', 1),
       'access arguments' => array('administer users'),
       'type' => MENU_LOCAL_TASK,
);
     return $items;
   }

